# esphome run garage-controller.yaml
# fonctionne correctement
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600  # Exécuté très tôt dans le processus de boot
    then:
      - light.turn_off: status_led

substitutions:
  name: garage-controller
  friendly_name: Garage controller
  
esp32:
  board: esp32-c5-devkitc-1
  framework:
    type: esp-idf

# Active le log pour debug
logger:
  baud_rate: 115200
  hardware_uart: UART0

# Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid24
  password: !secret wifi_password24
  #power_save_mode: none  # désactive l'économie d'énergie wifi (source fréquente de déco)
  ap:
    ssid: ${name} AP
    password: !secret wifi_password24

captive_portal:

# Définition de la LED RVB (GPIO 27)
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "LED Statut"
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    restore_mode: ALWAYS_OFF

# I2C pour le BMP280
i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true  # affiche les adresses I2C détectées dans les logs au boot

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic
    
  - platform: gpio # Capteur ouvert/fermé
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true  # résistance pull-up interne activée
      inverted: false  # fermé = contact fermé
    name: "Porte de garage"
    device_class: garage_door
    icon: "mdi:garage-open-variant"
    filters:
      - delayed_on: 50ms   # anti-rebond
      - delayed_off: 50ms
      
# Capteur BMP280
sensor:
  - platform: bmp280_i2c
    temperature:
      name: "Température garage"
      unit_of_measurement: "°C"
    pressure:
      name: "Pression garage"
      unit_of_measurement: "hPa"
    address: 0x76  # 0x76 par défaut, ou 0x77 si la broche SDO est reliée à VCC
    update_interval: 60s
    
switch:
  - platform: gpio
    pin: GPIO26
    id: garage_relay
    inverted: true
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: garage_relay

    
text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

# Define buttons for HA
button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config
  - platform: template
    name: "Ouvrir/fermer garage"
    icon: "mdi:garage-open-variant"
    id: open_close_garage
    on_press:
      - switch.turn_on: garage_relay
      

