# esphome run gwf-water-meter.yaml
# Compile OK!
# Version 2026-07-21
# update esphome en cli local: pip install -U esphome
# NE PAS UTILISER GPIO5 -> utilisé au boot
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600  # Exécuté très tôt dans le processus de boot
    then:
      - light.turn_off: status_led

substitutions:
  name: gwf-water-meter
  friendly_name: GWF Water Meter
  
esp32:
  board: esp32-c5-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_XTAL_FREQ_48: 'y'

# Active le log pour debug
logger:
  baud_rate: 115200
  hardware_uart: UART0

# Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid24
  password: !secret wifi_password24
  ap:
    ssid: ${name} AP
    password: !secret wifi_password24
    
# Webserver
web_server:
  port: 80
  version: 3
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

time:
  - platform: sntp
    id: time_sntp

external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [wmbus_radio, wmbus_meter, wmbus_common]

spi:
  clk_pin: GPIO7 # = SCLK
  mosi_pin: GPIO9
  miso_pin: GPIO8

#GD02 sur GPIO4, but not used.

wmbus_radio:
  radio_type: CC1101
  cs_pin: GPIO6 # = CSN
  irq_pin: GPIO3 # = GDO0
  frequency: 868.95MHz
  on_frame:
    - then:
        - logger.log:
            format: "RSSI: %ddBm T: %s (%d) %s"
            args: [ "frame->rssi()", "frame->as_hex().c_str()", "frame->data().size()", "toString(frame->link_mode())" ]

wmbus_meter:
  - id: water_meter
    meter_id: !secret gwf_water_meter_id
    type: gwfwater
    mode: C1
    key: !secret gwf_water_meter_aes_key
    #on_telegram:
    #  - logger.log:
    #      format: "GWF JSON: %s"
    #      args: ["meter.as_json().c_str()"]

sensor:
  - platform: wmbus_meter
    parent_id: water_meter
    field: total_m3
    name: "Consommation eau"
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    device_class: water
    state_class: total_increasing
    icon: "mdi:water"

  - platform: wmbus_meter
    parent_id: water_meter
    field: rssi_dbm
    name: "Eau RSSI"
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    device_class: signal_strength
    state_class: measurement
    entity_category: diagnostic

# Définition de la LED RVB (GPIO 27)
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "LED Statut"
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

# Define buttons for HA
button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config


